groups:
  - name: presence
    rules:
      - record: presence:trip_duration_seconds:last
        expr: (presence_last_return_timestamp - presence_last_leave_timestamp) > 0

      - record: presence:trip_duration_seconds:current
        expr: (presence_last_leave_timestamp - presence_last_return_timestamp) > 0
